### ISSUE TITLE
Is it working?

### ISSUE THREAD

**Issue by Claycorp** [gecgooden/chunkgen#14]
I currently have this installed on only the server.
I run the command and get no response saying it started or anything.
Running /chunkgen stop says it stopped but that's regardless of if a generator is running or not.

#3 says that progress updates were added but they never appear.

**Comment by gecgooden** [comment]
Can you upload the log from the server?

**Comment by Claycorp** [comment]
https://gist.github.com/Claycorp/8d1b0f7927f6dfd171a5

**Comment by spocane** [comment]
the default settings makes it pause while players are logged onto the server, so you need to change that setting or logout of the server and then it will start

**Comment by Claycorp** [comment]
Ah. This information isn't included anywhere on curse. So I had no idea. I don't need it anymore as i used something else.
