### ISSUE TITLE
Generate Features

### ISSUE THREAD

**Issue by Nightreaver** [gecgooden/chunkgen#19]
Hello

Does this mod also generate terrain features like trees, plants ect?

There are many mods outside just generating the chunk without features, but what also consumes a lot o processing power is the features ie. from BoP, sometimes when I reach an area that is heavy to generate and travel around, I get kicked out due to timeouts till everything is generated.

So I also like to generate features, is it possible?

Cheers

**Comment by gecgooden** [comment]
The mod should generate any additional terrain such as trees or plants, and any mod related world generation.

**Comment by Nightreaver** [comment]
I already have a worl generated  3000x3000 blocks, i wanted to test the chunkgen so i too my 3000 / 16, so get a the amount of chunks, around 188 chunks.

i did /chunkgen 0 0 180 180
but nothing really happend
i did /chunkgen 0 0 230 230 0 
it always takes longer, but nothing is generated, no new chunk files are popping up... it just takes time.

am I doing it wrong?
