### ISSUE TITLE
Trees not generating during chunkgen

### ISSUE THREAD

**Issue by plague006** [gecgooden/chunkgen#2]
When I pre-generate maps with the mod and then run mapping software such as JourneyMap (client-side) or DynMap (server-side) the results are maps that map out the biomes, but trees/foliage only appear where players have traveled.

Sample from JourneyMap: http://imgur.com/9atu8eo

Not sure exactly what to classify this as.. I don't see it quite as a bug.. maybe a feature request?

**Comment by gecgooden** [comment]
Finally got around to resolving this.
