### ISSUE TITLE
[1.10.2] No new chunks are generated

### ISSUE THREAD

**Issue by kerenon** [gecgooden/chunkgen#25]
I know it sounds strange, but it seems the mod pretends to be doing something, but actually it isn't (see link). It has log output, and the percentage goes up (and it eventually finishes), but the actual files on disk aren't touched. I've tried running `chunkgen radius 0 0 1000 0`, left it overnight and it completed without problems. Only the world on disk was 17 MB, and that's kinda impossible. Am I doing something wrong?

https://asciinema.org/a/5p8ljlqlqeczr57rmghdwag5h

**Comment by Teibidh** [comment]
I am having the same experience, command used was "chunkgen 0 0 200 200", I get plenty of output indicating what chunks are being generated, but when using "dynmap fullrender world" afterwards I get only the spawn area or chunks that I have actually walked through while logged in.

This is using MC 1.10.2 dedicated server with Forge 12.18.1.2089

**Comment by 4rz0** [comment]
I can confirm that issue.
The region files are generated but not populated.

**Comment by joshricker** [comment]
Can confirm also after building latest, all generated region files are 8kb.

**Comment by Kaeltis** [comment]
Can confirm this, exact same issue here.

**Comment by hiimcody1** [comment]
Can confirm this issue from my test server. Region files created, chunk data isn't.

**Comment by JoshuaRogers** [comment]
Created pull request #36 to address this issue.

**Comment by Baughn** [comment]
So that's done, but there hasn't been a release since. Can we have an 1.10 release on Curse?

**Comment by gecgooden** [comment]
Sure, I'll get to that in the next few days.

**Comment by Baughn** [comment]
I recommend adding a "Release on curse" task to your gradle config. You can take a look at https://github.com/Electrical-Age/ElectricalAge/blob/develop/build.gradle#L266 for how.

**Comment by gecgooden** [comment]
That's a great idea @Baughn, I'll definitely do that.

**Comment by gecgooden** [comment]
I've published the 1.5.0 release to CurseForge now. Closing this issue.
