### ISSUE TITLE
One of the passed arguments wasn't a number!

### ISSUE THREAD

**Issue by Pelirow** [gecgooden/chunkgen#30]
I get the above comment when trying to use the mod. Using 1.8.9, my Forge is 1808.

I type in:

/chunkgen zone 135 141 2500 2500 0

starting coords, amount of x and z chunks (40kx40k blocks), and dimension. I tried a bunch of other stuff but get the same comment. Any clarification is appreciated.

**Comment by ianc1215** [comment]
I am getting the same error when I try to generate a radius on a map. I am running 1.7.10 with Forge 1614.

**Comment by gecgooden** [comment]
The command for older versions should use the options described here: https://github.com/gecgooden/chunkgen/blob/c2c8de337cbcc27d3a9e8acc6f61c3bb4b738e05/README.md

I updated the README to use the current 1.10.2 versions arguments as I'm only supporting the latest version of chunkgen. I'll add a note to the README soon to note the arguments for older versions.
