### ISSUE TITLE
Entities and TileEntities not unloading.

### ISSUE THREAD

**Issue by marvin-bitterlich** [gecgooden/chunkgen#34]
I am currently generating a big area on my server using the pr #33 

But the number of entities and tileentities rises steady event with their respective chunks being unloaded. Is there a way to unload them too?

**Comment by Kostronor** [comment]
It seems the problem disappears when a player is on the server. Joining the server unloaded all entities.

**Comment by gecgooden** [comment]
As far as I'm aware, the Entities and TileEntities should unload when the chunk does. I'll look into it
