### ISSUE TITLE
Some chunks not populated

### ISSUE THREAD

**Issue by Barteks2x** [gecgooden/chunkgen#4]
Random lines of chunks are not populated. The issue is [here](https://github.com/Barteks2x/chunkgen/blob/eb01234e0e0d7050b4196441777415bbe9381a28/src/main/java/com/gecgooden/chunkgen/util/Utilities.java#L36). As I explaied in my comment to issue #2, you need to generate chunks at (x, z), (x+1, z), (x, z+1), (x+1, z+1). In any order.
The order doesn't matter because if you, for example, generate chunk at (x+1, z) it will also try to populate chunks at (x+1-1, z), (x+1, z-1), (x+1-1, z-1).
Your way mostly works because you don't explictly unload chunks. And apparently forge unloads them automatically.  And when forge unloads chunks - some newly generated chunks won't be populated.

**Comment by gecgooden** [comment]
I have changed the chunks loaded to the ones you specified, and the test version is here: https://dl.dropboxusercontent.com/u/6295002/chunkgen-1.7.10-1.2.2.jar
It looks like it works to me, can you test and make sure it does for you?

**Comment by Barteks2x** [comment]
It still doesn't seem to work correctly (tested with mcedit, generated 50x50 area). I decompiled the .jar file and I see why.
Before loading chunk you are checking if it's already loaded. But you only check if (x, z) is loaded, and then if it's not - generate chunks at (x+1, z), (x, z+1) and (x+1, z+1). So when you generate next chunk, (x+1, z), it will be already loaded. So it won't generate it again. And it won't generate chunks for population. The fix is to check existance of each chunk separately.

**Comment by gecgooden** [comment]
Ah, thats what I get for hastily coding.. 
This should do it: https://dl.dropboxusercontent.com/u/6295002/chunkgen-1.7.10-1.2.2b.jar

**Comment by Barteks2x** [comment]
Works perfectly.
