### ISSUE TITLE
Exception Generating Chunk, couldn't find realistic ver of biome

### ISSUE THREAD

**Issue by vedisdragon** [gecgooden/chunkgen#52]
Having an issue with the 1.7.10 edition: Somehow, biome 195, Thaumcraft Eldritchlands, tried to generate in the overworld and crashed the server.
I'm running a Cauldron 1.7.10 server. Any help to fix this, or at least to manually fix the "corrupted" chunks, would be fantastic!
Players will crash on log on, I teleported to the chunk to investigate and managed to crash the server.

Crash report:
https://drive.google.com/open?id=0B_vrOlC_nFXlR2tjQ3BvbXp3dzg

Additional info with server console:
https://docs.google.com/document/d/1zzEdgZSmmdlolrXxzcAcdqxX-eiy1gQMpJeaPVCbDIE/edit?usp=sharing

**Comment by gecgooden** [comment]
Sorry, I'm not supporting 1.7.10 anymore. 
I never tested chunkgen on Cauldron servers so it might not be compatible.

**Comment by vedisdragon** [comment]
Fixed by updating from 0.5 to 1.0 version of RTG 1.7.10, thanks for your work on this great mod!
