### ISSUE TITLE
[Feature Request] Allow fractional values for numChunksPerTick

### ISSUE THREAD

**Issue by utoc** [gecgooden/chunkgen#9]
I have a weird request.  We're using ExtrabiomesXL on our current map and it has some issues with decoration (namely biomes with a lot of leaves).  Anytime chunkgen gets to a chunk that ends up being a "leafy" biome, we end up with 9000ms-30000ms tick periods. (this is not an exaggeraton!)

It would be nice if somehow chunkgen could somehow allow fractional values so that instead of loading 1 defined by numChunksPerTick, I could specify something like .025, meaning it would load one chunk every 40 ticks.  I'm open to other solutions if you can think of something more efficient or easier to code.

**Comment by gecgooden** [comment]
I think it should be possible to do this, if we add in a config option so that we have a "generation delay" because I don't think that decimal values would work very well in numChunksPerTick.

**Comment by Baughn** [comment]
That's fixable. Give me a day, I'll try to get you a patch.
